import Link from "next/link";
import { Receipt, Search } from "lucide-react";
import { requirePerm } from "@/lib/auth";
import { db } from "@/lib/store";
import { AED, AEDshort, addDays, cx, fmtDate, titleCase, today } from "@/lib/utils";
import { Badge, Card, Empty, PageHead, Stat, Table, TD, TH } from "@/components/ui";

export const dynamic = "force-dynamic";

const PAGE_SIZE = 40;

export default async function PaymentsPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string; category?: string; page?: string }>;
}) {
  await requirePerm("payments.view");
  const sp = await searchParams;
  const q = (sp.q ?? "").trim().toLowerCase();
  const category = sp.category ?? "all";
  const page = Math.max(1, Number(sp.page ?? 1));

  const d = db();
  const contracts = new Map(d.contracts.map((c) => [c.id, c]));
  const tenants = new Map(d.tenants.map((t) => [t.id, t]));
  const units = new Map(d.units.map((u) => [u.id, u]));

  let rows = d.payments.map((p) => {
    const contract = contracts.get(p.contractId);
    const tenant = contract ? tenants.get(contract.tenantId) : undefined;
    const unit = contract ? units.get(contract.unitId) : undefined;
    return { p, contract, tenant, unit, user: d.users.find((u) => u.id === p.receivedBy) };
  });

  const totals = {
    all: d.payments.reduce((s, p) => s + p.amount, 0),
    rent: d.payments.filter((p) => p.category === "rent").reduce((s, p) => s + p.amount, 0),
    deposit: d.payments.filter((p) => p.category === "deposit").reduce((s, p) => s + p.amount, 0),
  };
  const last30 = d.payments
    .filter((p) => p.receivedAt >= addDays(today(), -30))
    .reduce((s, p) => s + p.amount, 0);

  if (category !== "all") rows = rows.filter((r) => r.p.category === category);
  if (q)
    rows = rows.filter(
      (r) =>
        r.p.receiptNo.toLowerCase().includes(q) ||
        (r.tenant?.name ?? "").toLowerCase().includes(q) ||
        (r.unit?.unitNo ?? "").toLowerCase().includes(q) ||
        r.p.reference.toLowerCase().includes(q)
    );

  rows.sort((a, b) => (a.p.receivedAt < b.p.receivedAt ? 1 : -1));

  const pages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE));
  const pageRows = rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const link = (params: Record<string, string | undefined>) => {
    const u = new URLSearchParams();
    Object.entries({ q: sp.q, category, ...params }).forEach(([k, v]) => {
      if (v && v !== "all") u.set(k, v);
    });
    const s = u.toString();
    return "/payments" + (s ? "?" + s : "");
  };

  return (
    <div>
      <PageHead
        title="Payments"
        sub="Receipts are generated by the system when a cheque clears or a payment is recorded — they are never typed by hand."
      />

      <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">
        <Stat label="Total received" value={AEDshort(totals.all)} sub={`${d.payments.length} receipts`} tone="good" />
        <Stat label="Rent" value={AEDshort(totals.rent)} sub="from cleared cheques" />
        <Stat label="Deposits held" value={AEDshort(totals.deposit)} sub="refundable to tenants" />
        <Stat label="Last 30 days" value={AEDshort(last30)} sub="cash collected" />
      </div>

      <Card padded={false}>
        <div className="flex flex-wrap items-center gap-3 border-b border-line px-5 py-3">
          <form action="/payments" className="relative">
            <input type="hidden" name="category" value={category} />
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              name="q"
              defaultValue={sp.q ?? ""}
              placeholder="Receipt, tenant, unit or reference…"
              className="h-9 w-72 rounded-lg border border-line bg-white pl-9 pr-3 text-[13px] outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/20"
            />
          </form>
          <div className="flex flex-wrap gap-1.5">
            {["all", "rent", "deposit", "commission", "fees", "maintenance"].map((c) => (
              <Link
                key={c}
                href={link({ category: c, page: undefined })}
                className={cx(
                  "rounded-lg border px-2.5 py-1.5 text-[12px] capitalize",
                  category === c ? "border-ink-900 bg-ink-900 text-white" : "border-line bg-white text-slate-600"
                )}
              >
                {c}
              </Link>
            ))}
          </div>
          <p className="tnum ml-auto text-[12.5px] text-slate-500">
            {rows.length.toLocaleString("en-US")} · {AED(rows.reduce((s, r) => s + r.p.amount, 0))}
          </p>
        </div>

        <div className="px-5 pb-4 pt-2">
          {pageRows.length === 0 ? (
            <Empty title="No payments match" icon={<Receipt size={22} />} />
          ) : (
            <Table>
              <thead>
                <tr>
                  <TH>Receipt</TH>
                  <TH>Date</TH>
                  <TH>Tenant</TH>
                  <TH>Unit</TH>
                  <TH>Category</TH>
                  <TH>Reference</TH>
                  <TH align="right">Amount</TH>
                </tr>
              </thead>
              <tbody>
                {pageRows.map((r) => (
                  <tr key={r.p.id}>
                    <TD className="tnum font-medium text-ink-900">{r.p.receiptNo}</TD>
                    <TD>{fmtDate(r.p.receivedAt)}</TD>
                    <TD className="max-w-[180px]">
                      {r.tenant ? (
                        <Link href={`/tenants/${r.tenant.id}`} className="block truncate hover:text-brand-600">
                          {r.tenant.name}
                        </Link>
                      ) : (
                        "—"
                      )}
                    </TD>
                    <TD>{r.unit?.unitNo ?? "—"}</TD>
                    <TD>
                      <Badge tone={r.p.category === "rent" ? "good" : "neutral"}>{titleCase(r.p.category)}</Badge>
                    </TD>
                    <TD className="max-w-[160px] truncate text-[11.5px] text-slate-500">{r.p.reference}</TD>
                    <TD align="right" className="tnum font-medium text-ink-900">
                      {AED(r.p.amount)}
                    </TD>
                  </tr>
                ))}
              </tbody>
            </Table>
          )}
        </div>

        {pages > 1 && (
          <div className="flex items-center justify-between border-t border-line px-5 py-3 text-[12.5px]">
            <span className="text-slate-500">Page {page} of {pages}</span>
            <div className="flex gap-2">
              <Link href={link({ page: String(Math.max(1, page - 1)) })} className={cx("rounded-lg border border-line px-3 py-1.5", page === 1 && "pointer-events-none opacity-40")}>
                Previous
              </Link>
              <Link href={link({ page: String(Math.min(pages, page + 1)) })} className={cx("rounded-lg border border-line px-3 py-1.5", page === pages && "pointer-events-none opacity-40")}>
                Next
              </Link>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}
